# Generated by Django 5.2.7 on 2025-11-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(default='MANALI NAILS', max_length=200)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Phone',
            new_name='phone',
        ),
    ]
