# Generated by Django 5.2.7 on 2025-11-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_remove_product_description_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
