# Generated by Django 5.2.7 on 2025-11-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
